.TH pacpartial 8
.SH NAME
pacpartial \- intelligently install packages with pacman after a refresh
.SH SYNOPSIS
.B pacpartial
[\fB\-cnv\fR] [\fB\-k \fIpackage\fR] [\fIpackage\fR...] [\fB\-D \fIpackage\fR...]
.SH DESCRIPTION
.B pacpartial
allows you to install and upgrade packages on a refreshed system (after \fBpacman \-Sy\fR).
It analyses the dependency tree to find a minimum set of packages that must be updated, to avoid breaks related to version changes.
.PP
It also provides an interactive way to "keep" packages, preventing them from updating, useful for large or frequently-updated packages.
.SH OPTIONS
See
.B pacpartial --help
for a description of options.
.SH FILES
.TP
.I /etc/pacman.d/partial_keep
A list of packages that should be version-kept, as if by using
.BR \-k / \-\-keep \.
.TP
.I /etc/pacman.d/partial_always
A list of packages that should always be updated if they are out-of-date.
In other words, append these packages to the command line.
.SH EXAMPLES
Refresh the databases and install a package, with some optional dependencies:
.PP
.nf
.RS
pacman -Sy
pacpartial package -D opt1 opt2
.RE
.fi
.PP
Check which packages would need downloading:
.PP
.nf
.RS
checkupdates
pacpartial -c package
.RE
.fi
.SH NOTES
Installing normally via
.B pacman \-S
should not be done on a refreshed system.

This program is not meant to fully replace complete system upgrades, which ensure all packages are up-to-date with any bugfixes and security patches.
It also does not guarantee that no breakages will occur, but simply avoids their most common causes.
.SH BUGS
Please report issues or requests on the Web at <https://github.com/tmewett/pacpartial>.
